=== nicolashaddad80/tp14/interfaces.dtd
<?xml version="1.0" encoding="UTF-8" ?>
	<!ELEMENT interfaces ((auto | iface)*)>
	<!ELEMENT auto (name+)>
	<!ELEMENT name EMPTY>
	<!ENTITY % addressIP "#PCDATA">
	<!ATTLIST name value IDREFS #REQUIRED>
	<!ELEMENT iface (inet)>
	<!ATTLIST iface name ID #REQUIRED>
	<!ELEMENT inet (loopback | dhcp | static)>
	<!ELEMENT loopback EMPTY>
	<!ELEMENT dhcp EMPTY>
	<!ATTLIST dhcp hostname CDATA #IMPLIED>
	<!ELEMENT static (address, netmask, gateway?)>
	<!ELEMENT address (%addressIP;)>
	<!ELEMENT netmask (%addressIP;)>
	<!ELEMENT gateway (%addressIP;)>

=== nicolashaddad80/tp14/xml/interfacesExemple1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE interfaces SYSTEM "interfaces.dtd">

<interfaces>
	<iface name="lo">
		<inet>
			<loopback/>
		</inet>
	</iface>				   	  
	<iface name="eth0">
		<inet>
			<dhcp/>
		</inet>
	</iface>
	<iface name="eth1">
		<inet>
			<static>
				<address>5.135.166.198</address>
				<netmask>255.255.255.255</netmask>
				<gateway>5.135.166.254</gateway>
			</static>
		</inet>
	</iface>
	<auto>
		<name value="lo"/>
	</auto>
	<auto>
		<name value="eth0"/>
		<name value="eth1"/>
	</auto>
</interfaces>

=== nicolashaddad80/tp14/interfacesExemple1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE interfaces SYSTEM "C:\Users\az01993\OneDrive - Alliance\Documents\01-Perso\CNAM_2019_2020\NFP121\tps\src\fr\cnam\tp14\interfaces.dtd">
<interfaces>
	<auto>
		<name value="lo"/>
	</auto>
	<iface name="lo">
		<inet>
			<loopback/>
		</inet>
	</iface>
	<auto>
		<name value="eth0"/>
		<name value="eth1"/>
	</auto>
	<iface name="eth0">
		<inet>
			<dhcp/>
		</inet>
	</iface>
	<iface name="eth1">
		<inet>
			<static>
				<address>
				5.135.166.198
				</address>
				
				<netmask>
				255.255.255.255
				</netmask>
				<gateway>
				5.135.166.254
				</gateway>
			</static>
		</inet>
	</iface>
</interfaces>
